# Generated by Django 5.1.2 on 2024-11-14 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publication_year', models.PositiveSmallIntegerField()),
                ('author', models.ForeignKey(help_text='Author of the book.', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='author.author')),
                ('genre', models.ForeignKey(help_text='Genre of the book.', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='genre.genre')),
            ],
        ),
    ]
