# Generated by Django 5.1.3 on 2024-11-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image_path',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
