# Generated by Django 5.1.2 on 2024-11-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_image_path'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('first_name', 'last_name')},
        ),
    ]
