# Generated by Django 5.1.2 on 2024-11-14 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('writing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('translators', models.ManyToManyField(help_text='Translators of the book.', related_name='translated_books', to='author.author')),
                ('writing', models.ForeignKey(help_text='Book writing.', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='writing.writing')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrowings', to='book.book')),
                ('reader', models.ForeignKey(limit_choices_to={'role': 'reader'}, on_delete=django.db.models.deletion.PROTECT, related_name='borrowings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='borrowers',
            field=models.ManyToManyField(blank=True, help_text='Users who have borrowed the book.', limit_choices_to={'role': 'reader'}, related_name='borrowed_books', through='book.Borrowing', to=settings.AUTH_USER_MODEL),
        ),
    ]
